pluginManagement {
    repositories {
        maven { url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        maven { url = 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.fabricmc.net/' }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        maven { url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        maven { url = 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
        maven { url = 'https://maven.blamejared.com' }
    }
}

rootProject.name = 'OrderToCook-Forge-1.20.1'

include 'common'
project(':common').projectDir = file('../common')
